name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
#          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via lftp
        env:
          HOST: ${{ secrets.FTP_SERVER }}
          USER: ${{ secrets.FTP_USERNAME }}
          PASS: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -c "set ftp:ssl-allow no; open -u $USER,$PASS $HOST; mirror -R ./out/ www/"
